//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPSReporting.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using GPSReporting.Models;
    using GPSReporting.Models.RTNReports;
    
    public partial class MGPSAPIEntities : DbContext
    {
        public MGPSAPIEntities()
            : base("name=MGPSAPIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DMCVehicleList> DMCVehicleLists { get; set; }
        public virtual DbSet<UserList> UserLists { get; set; }
        public virtual DbSet<TripReportRaw_vw> TripReportRaw_vw { get; set; }
        public virtual DbSet<LogList> LogLists { get; set; }
        public virtual DbSet<SpeedViolation_vw> SpeedViolation_vw { get; set; }
        public virtual DbSet<ExcessiveIdling_vw> ExcessiveIdling_vw { get; set; }
        public virtual DbSet<RTNVehicleList> RTNVehicleLists { get; set; }
        public virtual DbSet<vw_RTNTripReportRaw> vw_RTNTripReportRaw { get; set; }
    }
}
